import { 
  Brain, 
  HelpCircle, 
  ListTodo, 
  Layers, 
  FolderTree, 
  Package, 
  Database, 
  Code2, 
  Shield, 
  FileText, 
  TestTube, 
  Rocket, 
  GitBranch, 
  Cloud,
  LucideIcon
} from 'lucide-react';

export interface Agent {
  id: string;
  name: string;
  shortName: string;
  icon: LucideIcon;
  phase: string;
  purpose: string;
  description: string;
  does: string[];
  outputs: string[];
  restriction: string;
  color: string;
  bgColor: string;
}

export const COGNIX_AGENTS: Agent[] = [
  {
    id: 'requirement-analyzer',
    name: 'Requirement Analyzer Agent',
    shortName: 'Requirement Analyzer',
    icon: Brain,
    phase: 'Understanding',
    purpose: 'Converts user prompt into structured requirements',
    description: 'First agent to run. Analyzes natural language input and extracts structured engineering requirements.',
    does: [
      'Extract entities (User, Order, etc.)',
      'Detect auth, payments, tenancy',
      'Identify missing decisions',
      'Assign confidence score',
    ],
    outputs: ['Structured requirement draft', 'Clarification questions (if needed)'],
    restriction: 'Does NOT generate code',
    color: 'text-violet-500',
    bgColor: 'bg-violet-500/10',
  },
  {
    id: 'clarification',
    name: 'Clarification Agent',
    shortName: 'Clarification',
    icon: HelpCircle,
    phase: 'Decisions',
    purpose: 'Ask only necessary questions',
    description: 'Runs only if ambiguity exists. Prevents AI from guessing critical decisions.',
    does: [
      'Generate multiple-choice decisions',
      'Prevent AI guessing',
      'Lock in final requirements',
    ],
    outputs: ['Final locked requirements'],
    restriction: 'Does NOT design architecture',
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
  },
  {
    id: 'task-planner',
    name: 'Task Planner Agent',
    shortName: 'Task Planner',
    icon: ListTodo,
    phase: 'Planning',
    purpose: 'Break system into real engineering tasks',
    description: 'Engineering backbone. Creates actionable tasks with dependencies and assignments.',
    does: [
      'Create Kanban tasks',
      'Assign task IDs',
      'Define dependencies',
      'Map tasks to agents',
    ],
    outputs: ['Live Kanban board'],
    restriction: 'Does NOT write code',
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
  },
  {
    id: 'architecture-designer',
    name: 'Architecture Designer Agent',
    shortName: 'Architect',
    icon: Layers,
    phase: 'Design',
    purpose: 'Design system shape',
    description: 'Hard gate before code. Defines the modular monolith structure.',
    does: [
      'Define modules',
      'Set boundaries',
      'Decide API versioning',
      'Name conventions',
    ],
    outputs: ['Modular Monolith plan'],
    restriction: 'No code until human approval',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-500/10',
  },
  {
    id: 'scaffolding',
    name: 'Project Scaffolding Agent',
    shortName: 'Scaffolding',
    icon: FolderTree,
    phase: 'Structure',
    purpose: 'Create enterprise-grade folder structure',
    description: 'Generates deterministic project skeleton with clean architecture.',
    does: [
      'Generate .NET 8 solution',
      'Create modules',
      'Apply clean architecture layout',
    ],
    outputs: ['Deterministic project skeleton'],
    restriction: 'Does NOT install random libs',
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-500/10',
  },
  {
    id: 'dependency-manager',
    name: 'Dependency Manager Agent',
    shortName: 'Dependencies',
    icon: Package,
    phase: 'Libraries',
    purpose: 'Install safe, compatible libraries',
    description: 'Ensures only approved, version-pinned packages are installed.',
    does: [
      'Install .NET 8 compatible packages',
      'Pin versions',
      'Enforce approved list',
    ],
    outputs: ['Locked dependency graph'],
    restriction: 'No experimental packages',
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
  },
  {
    id: 'database-modeler',
    name: 'Database Modeling Agent',
    shortName: 'Database',
    icon: Database,
    phase: 'Data',
    purpose: 'Design persistence layer',
    description: 'Creates entity models, relationships, and migrations.',
    does: [
      'Create entities',
      'Define relationships',
      'Generate migrations',
      'Apply multi-tenancy rules',
    ],
    outputs: ['Database schema (Postgres)'],
    restriction: 'No business logic',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
  },
  {
    id: 'api-generator',
    name: 'API Generator Agent',
    shortName: 'API Generator',
    icon: Code2,
    phase: 'APIs',
    purpose: 'Build production APIs',
    description: 'Generates controllers, DTOs, and services following REST standards.',
    does: [
      'Generate controllers',
      'Create DTOs',
      'Implement services',
      'Apply REST standards',
    ],
    outputs: ['Working endpoints'],
    restriction: 'No security shortcuts',
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    id: 'security',
    name: 'Security Agent',
    shortName: 'Security',
    icon: Shield,
    phase: 'Security',
    purpose: 'Enforce security by default',
    description: 'Non-negotiable. Implements authentication and authorization.',
    does: [
      'JWT auth',
      'Refresh tokens',
      'RBAC',
      'Policies & scopes',
    ],
    outputs: ['Secure API surface'],
    restriction: 'AI cannot weaken security',
    color: 'text-red-500',
    bgColor: 'bg-red-500/10',
  },
  {
    id: 'documentation',
    name: 'Documentation Agent',
    shortName: 'Docs',
    icon: FileText,
    phase: 'Docs',
    purpose: 'Make APIs usable',
    description: 'Generates comprehensive API documentation.',
    does: [
      'Generate OpenAPI 3.1',
      'Swagger UI',
      'Example requests',
      'Postman collections',
    ],
    outputs: ['Live API documentation'],
    restriction: 'Must be accurate',
    color: 'text-slate-500',
    bgColor: 'bg-slate-500/10',
  },
  {
    id: 'testing',
    name: 'Testing Agent',
    shortName: 'Testing',
    icon: TestTube,
    phase: 'Quality',
    purpose: 'Validate correctness',
    description: 'Runs automated tests. Failures block progress.',
    does: [
      'Unit tests',
      'Auth tests',
      'Contract tests',
    ],
    outputs: ['Pass / fail results'],
    restriction: 'Failures block progress',
    color: 'text-purple-500',
    bgColor: 'bg-purple-500/10',
  },
  {
    id: 'sandbox-deploy',
    name: 'Sandbox Deployment Agent',
    shortName: 'Sandbox',
    icon: Rocket,
    phase: 'Runtime',
    purpose: 'Give user something real',
    description: 'Deploys to sandbox environment for testing.',
    does: [
      'Deploy to Railway / Render',
      'Configure sandbox mode',
      'Enable reset',
    ],
    outputs: ['Live sandbox URL'],
    restriction: 'No prod access',
    color: 'text-green-500',
    bgColor: 'bg-green-500/10',
  },
  {
    id: 'github-sync',
    name: 'GitHub Sync Agent',
    shortName: 'GitHub',
    icon: GitBranch,
    phase: 'Ownership',
    purpose: 'Make GitHub source of truth',
    description: 'Manages repository synchronization and version control.',
    does: [
      'Create / sync repo',
      'Commit all changes',
      'Track agent vs human edits',
      'Enable rollback',
    ],
    outputs: ['Full commit history'],
    restriction: 'Must track all changes',
    color: 'text-gray-500',
    bgColor: 'bg-gray-500/10',
  },
  {
    id: 'prod-deploy',
    name: 'Production Deployment Agent',
    shortName: 'Production',
    icon: Cloud,
    phase: 'Production',
    purpose: 'Handle real deployments',
    description: 'Final, gated agent. Cannot deploy without human approval.',
    does: [
      'Prepare diffs',
      'Validate configs',
      'Deploy to Azure or Fly.io',
    ],
    outputs: ['Production backend'],
    restriction: 'Cannot deploy without human approval',
    color: 'text-rose-500',
    bgColor: 'bg-rose-500/10',
  },
];

export const getAgentById = (id: string): Agent | undefined => {
  return COGNIX_AGENTS.find(agent => agent.id === id);
};

export const getAgentByPhase = (phase: string): Agent | undefined => {
  return COGNIX_AGENTS.find(agent => agent.phase === phase);
};

export const AGENT_PIPELINE_ORDER = [
  'requirement-analyzer',
  'clarification',
  'task-planner',
  'architecture-designer',
  'scaffolding',
  'dependency-manager',
  'database-modeler',
  'api-generator',
  'security',
  'documentation',
  'testing',
  'sandbox-deploy',
  'github-sync',
  'prod-deploy',
];
